---

name: "PHPUnit"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    container: php:8.2-alpine

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - uses: actions/checkout@v2

      - uses: ramsey/composer-install@v2
        with:
          dependency-versions: locked
          composer-options: "--no-scripts"

      - uses: ngmy/phive-install-action@master

      - run: "./resources/tools/phpunit --do-not-cache-result --coverage-cobertura ./phpunit.cobertura.xml --colors=never"

      - uses: 5monkeys/cobertura-action@master
        with:
          path: ./phpunit.cobertura.mxl
